#-----------------
# Versions
#-----------------
[versions]
kotlin = "1.8.10"
coroutines = "1.6.4"
mockk = "1.13.3"
junit5 = "5.8.1"

#-----------------
# Libraries
#-----------------
[libraries]
# Common libraries
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

# Test libraries
test-junit5 = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5"}
test-kotlin = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
test-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
test-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

#-----------------
# Plugins
#-----------------
[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }